# Generated by Django 5.2.9 on 2025-12-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_author_alter_comment_blogpost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='BlogPost',
            new_name='blog_post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
